name: learn-github-actions
on: [push]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      - uses: php-actions/phpunit@v2
        with:
          configuration: ./test/phpunit.xml
          # php_version: 7.3.25
      # - run: phpunit --testdox tests
      # - uses: actions/setup-node@v1
      # - run: npm install -g bats
      # - run: bats -v